<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr class="danger">
            <th>名前</th>
            <th>内容</th>
            <th>優先度</th>
            <th>状態</th>
            <th>予定(今週)</th>
            <th>実績(今週)</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($issues as $issue) : ?>
            <tr>
                <td>
                    <?php echo $this->escapeHtml($issue->getProjectName()); ?>
                </td>
                <td>
                    <?php echo $this->escapeHtml($issue->getSummary()); ?>
                </td>
                <td>
                    <?php echo $this->escapeHtml($issue->getPriority()); ?>
                </td>
                <td>
                    <?php echo $this->escapeHtml($issue->getStatus()); ?>
                </td>
                <td>
                    <?php echo $this->escapeHtml($issue->getThisWeekEstimatedHours()); ?>
                </td>
                <td>
                    <?php echo $this->escapeHtml($issue->getThisWeekActualHours()); ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>