<h1>工程管理</h1>
<table>
    <tr>
        <button onclick="location.href='<?php echo 'application/member'; ?>'"
                class="btn btn-primary btn-lg btn-block">
            Member (Week)
        </button>
    </tr>
    <tr>
        <button onclick="location.href='<?php echo 'application/membermonth'; ?>'"
                class="btn btn-primary btn-lg btn-block">
            Member (Month)
        </button>
    </tr>
    <tr>
        <button onclick="location.href='<?php echo 'application/project'; ?>'"
                class="btn btn-primary btn-lg btn-block">
            Project (Week)
        </button>
    </tr>
    <tr>
        <button onclick="location.href='<?php echo 'application/project/sum'; ?>'"
                class="btn btn-primary btn-lg btn-block">
            Project (Cost)
        </button>
    </tr>
</table>

<br>

<button onclick="location.href='<?php echo 'application/tally'; ?>'"
        type="button"
        class="btn btn-default">
    集計
</button>
