<h1>工程管理</h1>
<table>
    <tr>
        <button onclick="location.href='<?php echo 'application/member'; ?>'"
                class="btn btn-primary btn-lg btn-block">
            Member
        </button>
    </tr>
    <tr>
        <button onclick="location.href='<?php echo 'application/membermonth'; ?>'"
                class="btn btn-primary btn-lg btn-block">
            Member (Month)
        </button>
    </tr>
    <tr>
        <button onclick="location.href='<?php echo 'application/project'; ?>'"
                class="btn btn-primary btn-lg btn-block">
            Project
        </button>
    </tr>
</table>
